### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by felicia1the1goat** [mineblock11/Spoticraft#9]
my minecraft crashed after installing the mod. idk if the mod requires spotify to be opened but if so then it possibly crashed because i use pojav launcher 

this is the crash report:

---- Minecraft Crash Report ----
// You're mean.

Time: 2023-03-23 14:52:45
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'spoticraft'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.UnsatisfiedLinkError: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.cache/JNA/temp/jna13464057506413643327.tmp: dlopen failed: library "/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.cache/JNA/temp/jna13464057506413643327.tmp" needed or dlopened by "/data/data/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so" is not accessible for the namespace "classloader-namespace"
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1045)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015)
	at com.sun.jna.Native.<clinit>(Native.java:221)
	at com.github.winterreisender.webviewko.WebviewJNA$Companion.getLibOrNull(WebviewJNA.kt:74)
	at com.github.winterreisender.webviewko.WebviewJNA$Companion.getLib(WebviewJNA.kt:84)
	at com.github.winterreisender.webviewko.WebviewJNA$Companion.getLib$default(WebviewJNA.kt:84)
	at com.github.winterreisender.webviewko.WebviewKo.<init>(WebviewKo.kt:38)
	at com.github.winterreisender.webviewko.WebviewKo.<init>(WebviewKo.kt:42)
	at mine.block.spotify.SpotifyHandler.setup(SpotifyHandler.java:24)
	at mine.block.spoticraft.client.SpoticraftClient.onInitializeClient(SpoticraftClient.java:46)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (aarch64) version Android-13
	Java Version: 17.0.7-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 149200512 bytes (142 MiB) / 981467136 bytes (936 MiB) up to 981467136 bytes (936 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: 
	Identifier: 0x41 Family 8 Model 0xd05 Stepping r0x0p1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5445.83
	Virtual memory used (MB): 4626.77
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 2019.54
	JVM Flags: 3 total; -Xms936M -Xmx936M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Fabric Mods: 
		advanced_angle_assist: AdvancedAngleAssist 1.0.2
		animated-chunks: Animated Chunks 0.3.0
		armorchroma: Armor Chroma 1.2.3
		blockmeter: Block Meter 1.7
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		chatsounds: Chat Sounds 1.1.7
		cleardespawn: Clear Despawn 1.1.10
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		crop_marker: FullGrownCropMarker 1.19-1.2.0
		deathlog: DeathLog 0.2.11+1.19
		draggable-resource-packs: Draggable Resource Packs 3.0.0+build.6
		enhanced-searchability: Enhanced Searchability 3.0.0+build.6
		fabric-api: Fabric API 0.60.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.9+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.17+aeb40ebe90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.20+aeb40ebe90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.1+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.11+f71b366f90
			fabric-commands-v0: Fabric Commands (v0) 0.2.28+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.34+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.3+aeb40ebe90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.1+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.5+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.8+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.30+aeb40ebe90
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.18+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.28+aeb40ebe90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.28+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.21+aeb40ebe90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.7+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.28+aeb40ebe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.18+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.2+aeb40ebe90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.3+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.6+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.3+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.14+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.17+aeb40ebe90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.4+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.21+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.11+aeb40ebe90
			fabric-particles-v1: Fabric Particles (v1) 1.0.10+aeb40ebe90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.24+aeb40ebe90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.10+aeb40ebe90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.12+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.20+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.22+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.16+aeb40ebe90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.11+e62f51a390
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.26+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.13+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.20+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.11+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.0+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.9.2+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.17
		fancymenu: FancyMenu 2.13.3
		fastquit: FastQuit 2.1.0+1.19-1.19.2
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
		flighthelper: FlightHelper 1.19.1-fabric0.58.5-1.2.2
			gbfabrictools: GBfabrictools 1.3.4+1.19
		forgeconfigapiport: Forge Config API Port 4.2.11
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		hatlist: Hat List 1.3
		horsestatsvanilla: Horse Stats Vanilla 4.2.2
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		iceberg: Iceberg 1.0.46
		itemborders: Item Borders 1.1.6
		java: OpenJDK 64-Bit Server VM 17
		jumpoverfences: Jump Over Fences 1.1.0
		konkrete: Konkrete 1.6.0
		malilib: MaLiLib 0.13.0
		menumusic: Menu Music 1.1
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.2
		nametagping: NameTagPing 1.0-SNAPSHOT
		nbttooltips: NBT tooltips 0.1.4-1.19.x
		no-resource-pack-warnings: No Resource Pack Warnings 1.0.0
		no_fog: No Fog 1.3.2+1.16.5-1.19.3
		notifyme: Notify Me 1.0.1
		optionsreload: Options Reload 1.0.1
		prism: Prism 1.0.3
		quickconnectbutton: Quick Connect Button 1.2.1
		robinhood: Robin Hood 1.2.3
		skiptransitions: Skip Transitions 1.3.2+1.18.x
		slotlock: SlotLock 1.1.1-BETA+1.19
		spoticraft: Spoticraft 1.2.0
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.3
			com_github_winterreisender_webviewko-jvm: webviewko-jvm 0.6.0-SNAPSHOT
			com_neovisionaries_nv-i18n: nv-i18n 1.29
			net_spy_spymemcached: spymemcached 2.12.3
			org_apache_httpcomponents_client5_httpclient5: httpclient5 5.1.3
			org_apache_httpcomponents_client5_httpclient5-cache: httpclient5-cache 5.1.3
			org_apache_httpcomponents_core5_httpcore5: httpcore5 5.1.3
			org_ehcache_modules_ehcache-api: ehcache-api 3.4.0
			owo: oωo 0.8.5+1.19
				blue_endless_jankson: jankson 1.2.1
			se_michaelthelin_spotify_spotify-web-api-java: spotify-web-api-java 7.2.1
			spruceui: SpruceUI 4.0.0+1.19
		spu: Server Pack Unlocker 1.2
		textutilities: Text Utilities 1.4.2+1.19.2
		tnttime: TNT Time 1.1.0
		travelerstitles: Traveler's Titles 1.19.2-Fabric-3.1.0
		truesight: True Sight 1.0.0
		tweakermore: TweakerMore 3.10.0
			conditional-mixin: conditional mixin 0.3.2
		ukulib: ukulib 0.6.1+1.19.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			fabric-command-api-v2: Fabric Command API (v2) 2.1.10+93d8cb8290
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			gs_mclo_java_mclogs-java: mclogs-java 2.1.1
		visiblebarriers: Visible Barriers 1.5.3+1.19.x
		whoami: Who am I? 1.0
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.9
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by IMB11** [comment]
Only Linux, MacOS and Windows are supported.

Pojav launcher doesn't work because the webview api does not exist on android.
